Feature new dsl
zucchero-sintattico/pps-22-scatan pull request #39
Opened 2023-10-10 09:01 UTC by alemazzo

Introduced the new DSL to create game rules

2023-10-10 13:25 UTC, luigi-borriello00 reviewed
Please add some docs to this magic code :)

2023-10-10 18:08 UTC, manuandru requested changes

2023-10-10 18:08 UTC, manuandru commented on src/main/scala/scatan/lib/game/dsl/PropertiesDSL.scala
> +
Could we use `cats.Monad`?

2023-10-10 18:23 UTC, manuandru approved these changes
Next project, we will write a framework for pure functional programming 👽

2023-10-11 09:36 UTC, luigi-borriello00 approved these changes
How many times do you want to change the DSL? YES :)
Btw, great Job!

2023-10-11 09:37 UTC, merged