Feature steal card
zucchero-sintattico/pps-22-scatan pull request #43
Opened 2023-10-10 12:45 UTC by alemazzo

- Added steal card functionality to Scatan State
- Implemented Steal Effect
- Added steal functionality to Scatan Game
- Added steal button and popup to view

2023-10-10 13:36 UTC, luigi-borriello00 reviewed
Please, change the stealing in order to steale only to players that have buildings in that exagon

2023-10-10 18:14 UTC, manuandru requested changes

2023-10-10 18:14 UTC, manuandru commented on src/main/scala/scatan/views/game/components/StealCardPopup.scala
> +  def userSelectionPopup(): DisplayableSource[ReactiveHtmlElement.Base] =
```suggestion
  def userSelectionPopup(): DisplayableSource[Element] =
```

2023-10-11 13:32 UTC, luigi-borriello00 requested changes

2023-10-11 13:32 UTC, luigi-borriello00 commented on src/main/scala/scatan/model/game/ops/CardOps.scala
> +        val updatedVictimResourceCards = victimResourceCards.filterNot(_ == stolenCard)
Are you sure that this `filterNot` doesn't take all the cards of the same type of **stolenCard** instead of taking only that one?

2023-10-11 13:38 UTC, luigi-borriello00 requested changes

2023-10-11 13:38 UTC, luigi-borriello00 commented on src/main/scala/scatan/views/game/components/StealCardPopup.scala
> +      zIndex := 1000,
To be consistent with the rest of the project, please move this style properties inside the `style.css` file :)

2023-10-11 14:44 UTC, luigi-borriello00 approved these changes

2023-10-11 14:44 UTC, luigi-borriello00 approved these changes

2023-10-11 17:49 UTC, manuandru approved these changes

2023-10-11 17:49 UTC, manuandru commented on style.css
> +    z-index: 1000; */
We need this comment?

2023-10-11 17:56 UTC, manuandru approved these changes

2023-10-11 17:56 UTC, manuandru commented on style.css
>  }
We need new line at the end :)

2023-10-12 07:08 UTC, merged