Trades, chores and bug fixes
zucchero-sintattico/pps-22-scatan pull request #45
Opened 2023-10-10 18:54 UTC by luigi-borriello00

- Implement trades between players
- Implement trades with bank
- Show Current awards in GameView
- Add `partialScoresWithVictoryPoints` in Scores
- Bug Fixes

2023-10-11 10:11 UTC, alemazzo approved these changes
Good Job!

2023-10-11 17:55 UTC, manuandru requested changes

2023-10-11 17:55 UTC, manuandru commented on src/main/scala/scatan/model/components/ResourceCard.scala
> +
This could be something related to view aspect -- we need it in model?

2023-10-11 17:55 UTC, manuandru commented on style.css
>  }
We need new line at the end :)

2023-10-12 12:47 UTC, manuandru approved these changes
👍

2023-10-12 12:49 UTC, merged