Feature refactor ops
zucchero-sintattico/pps-22-scatan pull request #46
Opened 2023-10-12 16:50 UTC by luigi-borriello00

Just make this changes:
- Unpack the CardOps in ResCardOps and DevCardOps like `test` packages
- Fix all imports and adjust name conventions

2023-10-12 20:51 UTC, manuandru requested changes

2023-10-12 20:51 UTC, manuandru commented on src/main/scala/scatan/model/game/ops/DevCardOps.scala
> +object DevCardOps:
Consider

```suggestion
object DevelopmentCardOps:
```
in order to be esplicative

2023-10-12 20:51 UTC, manuandru commented on src/main/scala/scatan/model/game/ops/ResCardOps.scala
> +object ResCardOps:
```suggestion
object ResourceCardOps:
```

2023-10-13 07:13 UTC, alemazzo approved these changes

2023-10-13 15:38 UTC, manuandru approved these changes
Nice refactor!

2023-10-13 16:09 UTC, merged